name: spotit
description: A citizen issue reporting app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.3.0
  location: ^6.0.2
  url_launcher: ^6.3.0
  google_sign_in: ^6.2.1
  firebase_storage: ^12.3.0
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  lottie: ^3.3.2
  pull_to_refresh_notification: ^3.1.1
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/images/login_illustration.png
    - assets/images/google_icon.png

    

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  min_sdk_android: 21
